- name: installation du jdk8
  package: name=openjdk-8-jdk-headless state=present

- name: creation du compte wildfly
  user:
    name: wildfly
    shell: /bin/false
    system: yes
    home: /home/wildfly

- name: creation du repertoires pour wildfly
  file:
    path: '{{wildfly_etc}}'
    state: directory
    owner: wildfly
    group: wildfly

- name: installation de wildfly
  unarchive:
    src: '{{wildfly_url}}'
    dest: '{{wildfly_war}}'
    group: wildfly
    owner: wildfly
    remote_src: yes

- name: creation du lien symbolique
  file:
    src: /opt/wildfly-11.0.0.Final
    dest: /opt/wildfly 
    state: link

- name: Copy des fichiers1
  copy:
    src: /opt/wildfly/docs/contrib/scripts/systemd/wildfly.conf
    dest: /etc/wildfly
    owner: wildfly
    group: wildfly
    remote_src: yes

- name: Copy des fichiers 2
  copy:
    src: /opt/wildfly/docs/contrib/scripts/systemd/wildfly.service
    dest: /etc/systemd/system
    owner: wildfly
    remote_src: yes

- name: Copy des fichiers 3
  copy:
    src: /opt/wildfly/docs/contrib/scripts/systemd/launch.sh
    dest: /opt/wildfly/bin
    owner: wildfly
    group: wildfly
    mode: 0755
    remote_src: yes

- name: Enregistrer le service dans deamonds
  systemd:
    name: wildfly
    enabled: yes
    masked: no

- name: Démarrage du service wildfly
  systemd:
    state: restarted
    daemon_reload: yes
    name: wildfly

- name: Verif service demarrer
  systemd: state=started name=wildfly
